select * from customer;

--Q1. What is the total revenue generated by male vs female customers?
select gender,SUM(purchase_amount_usd) AS revenue_generated
FROM customer
GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount.
select customer_id, purchase_amount_usd
From customer
Where discount_applied = 'Yes' 
and purchase_amount_usd >= (select AVG(purchase_amount_usd)
from customer);

SELECT customer_id,
       purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount_usd >= (
      SELECT AVG(purchase_amount_usd)
      FROM customer
);

--Q3. Which are the top 5 products with highest average review ratings?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC 
LIMIT 5;

--Q4. Comapre the average purchase amounts between standard and express shipping?
SELECT shipping_type, ROUND(AVG(purchase_amount_usd),2) AS average_purchse
FROM customer
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;

--Q5. Do subscribed customer spend more? Compare average spend and the total revenue between subscribers and non subscribers ? 
SELECT subscription_status,
COUNT (customer_id) as total_customer,
ROUND(AVG(purchase_amount_usd),2) as avg_spend,
ROUND(SUM(purchase_amount_usd),2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend, total_revenue desc;

--Q6. Which 5 products have the highest percetage of purchase with discount applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) ,2) as discount_rate
FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into new, Returning, and loyal based on their total number of previous purchases,
--and show the count of each segment.
WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
From customer
)
select customer_segment, count (*) as number_of_customers
From customer_type 
Group by customer_segment;

--Q8. What are the top 3 most purchased produts with each category?
SELECT * FROM 

(SELECT category,item_purchased, COUNT(customer_id),
 DENSE_Rank()OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as rn
 FROM customer
 GROUP BY category,item_purchased)

WHERE rn <= 3;

--with CTE and ROW_NUMBER
With item_counts as (

SELECT category,item_purchased,
COUNT (customer_id) as total_orders,
ROW_NUMBER()OVER(Partition by category order by count(customer_id) DESC) as item_rank
FROM customer 
GROUP BY category, item_purchased)

select category,item_purchased,total_orders,item_rank
FROM item_counts
WHERE item_rank <=3; 

--Q9. Are customers who are repeat buyers (more than 5 previous purchase) 
--also likely to subscribe ?
SELECT subscription_status, 
COUNT(customer_id) as repeat_buyers
FROM customer 
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?
SELECT age, SUM(purchase_amount_usd) as revenue_contribution
FROM customer
GROUP BY age
ORDER BY age DESC;

with age_group as (
Select age, purchase_amount_usd,
case when age between 18 and 30 Then 'Young'
     when age between  31 and 50 Then 'Middle'
     Else 'old' end as age_group
FROM customer)

select age_group, SUM(purchase_amount_usd)
from age_group
group by age_group;

--with subquery
SELECT age_group, SUM(purchase_amount_usd) as rev
FROM

(Select age,purchase_amount_usd,
case when age between 18 and 30 Then 'Young'
     when age between  31 and 50 Then 'Middle'
     Else 'old' end as age_group
FROM customer
)
GROUP BY age_group


